apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: satyendransit12/orderservice:1.2.1
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: database-name
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: database-orderdb-host
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: jaeger-host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: database-user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: database-password