apiVersion: apps/v1
kind: Deployment
metadata:
    name: userdb-mysql
    labels:
        app: userdb-mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: userdb-mysql
    template:
        metadata:
            labels:
                app: userdb-mysql
        spec:
            containers:
            -   image: mysql:5.6
                name: userdb-mysql
                args:
                    - "--default-authentication-plugin=mysql_native_password"
                env:
                - name: MYSQL_ROOT_PASSWORD
                   valueFrom:
                    secretKeyRef:
                        name: dbsecrets
                        key: database-password
                ports:
                 - containerPort: 3306
                   name: userdb-mysql
                volumeMounts:
                    - name: userdb-mysql-persistent-storage
                      mountPath: /var/lib/mysql
            volumes:
                - name: userdb-mysql-persistent-storage
                  persistentVolumeClaim:
                    claimName: userdb
                